
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: api-votaciones
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_NAME=sistema_votaciones
      - DB_USER=root
      - DB_PASS=admin

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: sistema_votaciones
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
